[a,b,c,d,e,f]=readvars('data.dat');
display(a);
ft = fittype('a+b*c^x',...
    'dependent',{'y'},'independent',{'x'},...
    'coefficients',{'a','b','c'});
fit_given_cols(a,c,[.2 .2 .7 .3],"Modello","Northwest","$M$","Tempi di calcolo (s)","red",[1 10],false,[.1 .1 1],ft)


% ft = fittype('a+b*x',...
%     'dependent',{'y'},'independent',{'x'},...
%     'coefficients',{'a','b'});
% fit_given_cols(a,e,[.65 .1 .7 .3],"Modello","Northwest","$M$","Tempi di calcolo (s)","red",[1 10],false,[.1 .1 ],ft)